// <auto-generated />
namespace SurveyApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedsurveygroupmappingtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedsurveygroupmappingtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201606211101177_added survey group mapping table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
