// <auto-generated />
namespace SurveyApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedSurveynameinsurveygroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedSurveynameinsurveygroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201606211017494_added Survey name in survey group"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
