// <auto-generated />
namespace SurveyApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedanalystIdtoclient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedanalystIdtoclient));
        
        string IMigrationMetadata.Id
        {
            get { return "201607111020456_added analyst Id to client"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
