// <auto-generated />
namespace SurveyApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedsurveyanswerstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedsurveyanswerstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201606270624376_added survey answers table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
